### ISSUE TITLE
presentation related tasks

### ISSUE THREAD

**Issue by Nishchitagaddam** [Nishchitagaddam/Pyramid-Project#2]

**Comment by Nishchitagaddam** [comment]
[presentation (1).pdf](https://github.com/Nishchitagaddam/Pyramid-Project/files/674397/presentation.1.pdf)

**Comment by priyavemasani** [comment]
Done with the task
[presentation.pdf](https://github.com/Nishchitagaddam/Pyramid-Project/files/675583/presentation.pdf)
